import { hasLineBreak } from "@/lib/validators/single-line";

/**
 * Pure helpers for the "link or create a contact" decision when capturing a lead
 * (doc 02 §C4 "link/create contact (dedup applies)"). Kept out of the "use
 * server" action file so they are unit-testable.
 */

export type LeadContactMode = "link" | "create" | "none";

/**
 * How the lead should resolve its contact:
 *  - "link"   an existing contact was picked (id wins over any typed details)
 *  - "create" no existing contact, but a new enquirer's name was entered
 *  - "none"   neither — the lead is captured without a contact
 */
export function leadContactMode(input: {
  contactId?: string | null;
  newContactName?: string | null;
}): LeadContactMode {
  if (input.contactId) return "link";
  if (input.newContactName && input.newContactName.trim()) return "create";
  return "none";
}

/**
 * Split a free-typed enquirer name into first/last for the contacts row. The
 * first whitespace-run splits; everything after it is the surname. A single
 * token is a first name only. `display_name` is generated by the DB from these.
 */
export function splitEnquirerName(name: string): { firstName: string; lastName: string | null } {
  const trimmed = name.trim().replace(/\s+/g, " ");
  const gap = trimmed.indexOf(" ");
  if (gap === -1) return { firstName: trimmed, lastName: null };
  return { firstName: trimmed.slice(0, gap), lastName: trimmed.slice(gap + 1) };
}

export interface ParsedWebsiteEnquiry {
  name: string;
  email: string | null;
  phone: string | null;
  /**
   * The reference the visitor TYPED (0101), without the door's
   * "(no published listing with that reference)" note. The alert worker
   * rebuilds the desk e-mail from the lead and needs the same "About:" the
   * route used to send from the request body.
   */
  about: string | null;
}

/**
 * Why a header that opens with the door's marker cannot be trusted
 * (T-enquiry-identity-single-line). Each is a shape the doors never write:
 *  - `unknown_line`      a header line that is not `Name|Email|Phone|About: …`
 *                        (case B: a name carrying extra lines)
 *  - `duplicate_label`   a label twice (case A: a phone carrying `Email: …`)
 *  - `out_of_order`      labels out of Name → Email → Phone → About order
 *  - `stray_line_break`  a CR, or another Unicode line break, inside a value
 *  - `empty_value`       a label with nothing after it
 *  - `missing_name`      no Name line first
 *  - `no_contact`        neither Email nor Phone — the door has refused that
 *                        since 0084, so a blank line inside the name has
 *                        pushed the real ones below the header
 */
export type WebsiteEnquiryAmbiguity =
  | "unknown_line"
  | "duplicate_label"
  | "out_of_order"
  | "stray_line_break"
  | "empty_value"
  | "missing_name"
  | "no_contact";

export type WebsiteEnquiryReading =
  | { kind: "parsed"; person: ParsedWebsiteEnquiry }
  /** not the door's block at all: desk-typed, redacted, empty */
  | { kind: "not_website" }
  /** the door's marker, but a header nobody can read without guessing */
  | { kind: "ambiguous"; reason: WebsiteEnquiryAmbiguity };

const LABELS = ["Name", "Email", "Phone", "About"] as const;
type Label = (typeof LABELS)[number];
const LABEL_LINE = /^(Name|Email|Phone|About): ([^]*)$/;

/**
 * The door writes LF. A block typed on Windows arrives as CRLF THROUGHOUT and
 * has always been read (a desk-typed lead); it is the only CR this reader
 * forgives. A CR anywhere else — mixed in with the door's LFs — came from a
 * value, and stays in the line to be refused.
 */
function uniformLineEnds(message: string): string {
  const crlf = message.match(/\r\n/g)?.length ?? 0;
  if (crlf === 0) return message;
  const cr = message.match(/\r/g)?.length ?? 0;
  const lf = message.match(/\n/g)?.length ?? 0;
  return crlf === cr && crlf === lf ? message.replace(/\r\n/g, "\n") : message;
}

/**
 * The person behind a website enquiry, read from the block the doors write
 * (0084, kept by 0092/0096/0098/0101; the proposal door 0106; audit LR-08):
 *
 *   Website enquiry
 *   Name: …
 *   Email: …          (when given)
 *   Phone: …          (when given)
 *   About: …          (a typed reference; always, from a proposal)
 *   <blank>
 *   <the visitor's own words>
 *
 * THE DOORS' GRAMMAR, EXACTLY (T-enquiry-identity-single-line). The header is
 * every line up to the first empty one: Name first, then Email, Phone and
 * About at most once each and in that order, each with a value on its one
 * line, and at least one way to reply. Anything else is AMBIGUOUS — never
 * the last value for a label, never a line skipped, never a window that
 * stops looking — because until 0114 a line break in a value wrote a line
 * of its own, and the old reader turned that into someone else's e-mail
 * (case A) or no e-mail at all (case B). Nothing below the header is ever
 * read for identity: "Email: my old one bounced" in the visitor's words is
 * words. Ambiguous is not repaired either; the message is left whole for a
 * person to read.
 *
 * What this cannot see: a break that forged a PERFECT header (a name of
 * "Ann\nEmail: x@y" when no e-mail was given) is the same bytes as a real
 * one. The input rule (lib/validators/single-line.ts, 0114) is the fix; this
 * reader is the backstop for what was stored before it.
 */
export function readWebsiteEnquiry(message: string | null | undefined): WebsiteEnquiryReading {
  if (!message) return { kind: "not_website" };
  const lines = uniformLineEnds(message).split("\n");
  if (lines[0]?.trim() !== "Website enquiry") return { kind: "not_website" };

  const end = lines.indexOf("", 1);
  const header = lines.slice(1, end === -1 ? lines.length : end);
  const values: Partial<Record<Label, string>> = {};
  let last = -1;
  for (const line of header) {
    const m = LABEL_LINE.exec(line);
    if (!m) return { kind: "ambiguous", reason: "unknown_line" };
    const label = m[1] as Label;
    const at = LABELS.indexOf(label);
    if (values[label] !== undefined) return { kind: "ambiguous", reason: "duplicate_label" };
    if (last === -1 && label !== "Name") return { kind: "ambiguous", reason: "missing_name" };
    if (at <= last) return { kind: "ambiguous", reason: "out_of_order" };
    // before the trim, which would drop a CR at the end of the line
    if (hasLineBreak(m[2]!)) return { kind: "ambiguous", reason: "stray_line_break" };
    const value = m[2]!.trim();
    if (!value) return { kind: "ambiguous", reason: "empty_value" };
    values[label] = value;
    last = at;
  }
  if (values.Name === undefined) return { kind: "ambiguous", reason: "missing_name" };
  if (values.Email === undefined && values.Phone === undefined) return { kind: "ambiguous", reason: "no_contact" };

  return {
    kind: "parsed",
    person: {
      name: values.Name,
      email: values.Email ?? null,
      phone: values.Phone ?? null,
      // the door appends its own note when the typed reference matched nothing
      about: values.About?.replace(/\s*\(no published listing with that reference\)\s*$/, "").trim() || null,
    },
  };
}

/**
 * The person, or null when there is no one to read reliably — not the door's
 * block, or an ambiguous header (readWebsiteEnquiry). Every consumer treats
 * null as "the desk links or creates the contact by hand": the desk alert and
 * the escalation cancel as `lead_unreadable`, "Possible existing contact"
 * says the details could not be read, and "Create contact" refuses.
 */
export function parseWebsiteEnquiry(message: string | null | undefined): ParsedWebsiteEnquiry | null {
  const read = readWebsiteEnquiry(message);
  return read.kind === "parsed" ? read.person : null;
}

/**
 * The visitor's own words, read from the same block: everything after the
 * first blank line that ends the header. Null when they typed none (an
 * enquiry may be a reference alone) and for anything that is not the block.
 */
export function websiteEnquiryBody(message: string | null | undefined): string | null {
  if (!message) return null;
  const text = message.replace(/\r\n?/g, "\n");
  if (!text.startsWith("Website enquiry\n")) return null;
  const gap = text.indexOf("\n\n");
  if (gap === -1) return null;
  const body = text.slice(gap + 2).trim();
  return body || null;
}
