/**
 * Pure helpers for the "link or create a contact" decision when capturing a lead
 * (doc 02 §C4 "link/create contact (dedup applies)"). Kept out of the "use
 * server" action file so they are unit-testable.
 */

export type LeadContactMode = "link" | "create" | "none";

/**
 * How the lead should resolve its contact:
 *  - "link"   an existing contact was picked (id wins over any typed details)
 *  - "create" no existing contact, but a new enquirer's name was entered
 *  - "none"   neither — the lead is captured without a contact
 */
export function leadContactMode(input: {
  contactId?: string | null;
  newContactName?: string | null;
}): LeadContactMode {
  if (input.contactId) return "link";
  if (input.newContactName && input.newContactName.trim()) return "create";
  return "none";
}

/**
 * Split a free-typed enquirer name into first/last for the contacts row. The
 * first whitespace-run splits; everything after it is the surname. A single
 * token is a first name only. `display_name` is generated by the DB from these.
 */
export function splitEnquirerName(name: string): { firstName: string; lastName: string | null } {
  const trimmed = name.trim().replace(/\s+/g, " ");
  const gap = trimmed.indexOf(" ");
  if (gap === -1) return { firstName: trimmed, lastName: null };
  return { firstName: trimmed.slice(0, gap), lastName: trimmed.slice(gap + 1) };
}

export interface ParsedWebsiteEnquiry {
  name: string;
  email: string | null;
  phone: string | null;
  /**
   * The reference the visitor TYPED (0101), without the door's
   * "(no published listing with that reference)" note. The alert worker
   * rebuilds the desk e-mail from the lead and needs the same "About:" the
   * route used to send from the request body.
   */
  about: string | null;
}

/**
 * The person behind a website enquiry, read from the block the door writes
 * (0084, kept by 0092/0096/0098; audit LR-08):
 *
 *   Website enquiry
 *   Name: …
 *   Email: …          (when given)
 *   Phone: …          (when given)
 *   About: …          (when a reference was typed)
 *   <blank>
 *   <the visitor's own words>
 *
 * HEADER LINES ONLY. The reader stops at the first blank line and never looks
 * past the fifth, so a visitor who writes "Email: my old one bounced" in the
 * message body cannot be mistaken for the header. Anything that does not open
 * with the marker — a desk-typed lead, a redacted one — is null, and the desk
 * links or creates the contact by hand as before.
 */
export function parseWebsiteEnquiry(message: string | null | undefined): ParsedWebsiteEnquiry | null {
  if (!message) return null;
  const lines = message.replace(/\r\n?/g, "\n").split("\n");
  if (lines[0]?.trim() !== "Website enquiry") return null;

  let name: string | null = null;
  let email: string | null = null;
  let phone: string | null = null;
  let about: string | null = null;
  for (const line of lines.slice(1, 6)) {
    if (line.trim() === "") break;
    const m = /^(Name|Email|Phone|About): (.*)$/.exec(line);
    if (!m) continue;
    const value = m[2]!.trim() || null;
    if (m[1] === "Name") name = value;
    else if (m[1] === "Email") email = value;
    else if (m[1] === "Phone") phone = value;
    // the door appends its own note when the typed reference matched nothing
    else if (m[1] === "About")
      about = value?.replace(/\s*\(no published listing with that reference\)\s*$/, "").trim() || null;
  }
  if (!name) return null;
  return { name, email, phone, about };
}

/**
 * The visitor's own words, read from the same block: everything after the
 * first blank line that ends the header. Null when they typed none (an
 * enquiry may be a reference alone) and for anything that is not the block.
 */
export function websiteEnquiryBody(message: string | null | undefined): string | null {
  if (!message) return null;
  const text = message.replace(/\r\n?/g, "\n");
  if (!text.startsWith("Website enquiry\n")) return null;
  const gap = text.indexOf("\n\n");
  if (gap === -1) return null;
  const body = text.slice(gap + 2).trim();
  return body || null;
}
