/**
 * Pure helpers for the "link or create a contact" decision when capturing a lead
 * (doc 02 §C4 "link/create contact (dedup applies)"). Kept out of the "use
 * server" action file so they are unit-testable.
 */

export type LeadContactMode = "link" | "create" | "none";

/**
 * How the lead should resolve its contact:
 *  - "link"   an existing contact was picked (id wins over any typed details)
 *  - "create" no existing contact, but a new enquirer's name was entered
 *  - "none"   neither — the lead is captured without a contact
 */
export function leadContactMode(input: {
  contactId?: string | null;
  newContactName?: string | null;
}): LeadContactMode {
  if (input.contactId) return "link";
  if (input.newContactName && input.newContactName.trim()) return "create";
  return "none";
}

/**
 * Split a free-typed enquirer name into first/last for the contacts row. The
 * first whitespace-run splits; everything after it is the surname. A single
 * token is a first name only. `display_name` is generated by the DB from these.
 */
export function splitEnquirerName(name: string): { firstName: string; lastName: string | null } {
  const trimmed = name.trim().replace(/\s+/g, " ");
  const gap = trimmed.indexOf(" ");
  if (gap === -1) return { firstName: trimmed, lastName: null };
  return { firstName: trimmed.slice(0, gap), lastName: trimmed.slice(gap + 1) };
}
