/**
 * "Create similar" — turn an existing property into a starting point for a new
 * one (BACKLOG: *Create similar, S*).
 *
 * PURE. No I/O, so the rules about what carries and what must not are testable,
 * and the list of what was dropped is derived rather than remembered.
 *
 * NOTHING IS CREATED UNTIL THE USER SUBMITS. The seed rides in on
 * `/properties/new?similar=<id>` and only prefills the wizard. Creating a draft
 * copy on click would have been less code and would burn a REFERENCE every time
 * somebody changed their mind — `reference_counters` never reuses one, so an
 * abandoned draft leaves a permanent hole in the sequence the desk quotes from.
 *
 * WHAT IS DELIBERATELY NOT CARRIED
 *   * `reference`  — generated by `next_reference` on insert, and it never
 *                    changes afterwards. Copying it is not even possible.
 *   * `status`     — a new listing starts where the form starts it. Inheriting
 *                    `sold` would be absurd; inheriting `available` would be a
 *                    claim nobody made.
 *   * unit fields  — `unit_number`, `block`, `floor`, and the parent link. A
 *                    unit belongs to a project and is created from the project
 *                    page; a copy that kept the number would collide, and one
 *                    that kept the parent would smuggle a unit in through the
 *                    standalone form.
 *   * coordinates  — an exact point is a claim about THIS building. The copy is
 *                    a different building, so it starts without one and earns
 *                    its own.
 *
 * WHAT IS CARRIED, INCLUDING PRICE. A developer adding the sixth identical
 * villa wants the price, the areas and the bed/bath counts — that is the whole
 * point of the feature. The risk is that a prefilled field is accepted without
 * being read, so the page SAYS it is prefilled and names the source; a silent
 * copy would be the dangerous version.
 */

/** The columns the seed reads. Kept narrow on purpose — see the drop list. */
export interface SeedSource {
  reference: string;
  kind: string;
  property_type: string | null;
  transaction_type: string | null;
  district_id: string | null;
  area_id: string | null;
  address: string | null;
  title: unknown;
  asking_price: number | string | null;
  rent_price_month: number | string | null;
  plot_area_sqm: number | string | null;
  covered_area_sqm: number | string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  internal_notes: string | null;
  owner_contact_id: string | null;
  developer_contact_id: string | null;
}

export interface PropertySeed {
  /** the reference this was copied from — named on the page, never stored */
  fromReference: string;
  source: "owner" | "developer";
  partyId: string | null;
  kind: string;
  propertyType: string;
  transactionType: string;
  districtId: string;
  areaId: string;
  address: string;
  titleEn: string;
  askingPrice: string;
  rentPriceMonth: string;
  plotAreaSqm: string;
  coveredAreaSqm: string;
  bedrooms: string;
  bathrooms: string;
  internalNotes: string;
  /** human-readable list of what did NOT come across, shown on the page */
  dropped: string[];
}

/** The kinds the create wizard can actually make; units come from a project. */
const CREATABLE = new Set(["standalone", "project"]);

/**
 * Form fields want strings. `numeric` arrives from PostgREST as a STRING
 * already, and `0` is a legitimate value that `|| ""` would erase.
 */
const str = (v: number | string | null | undefined): string =>
  v === null || v === undefined ? "" : String(v);

export function buildPropertySeed(src: SeedSource): PropertySeed {
  const dropped = ["reference (a new one is generated)", "status", "map coordinates"];

  // A unit or a phase cannot be recreated through this form at all, so the copy
  // becomes a standalone listing and says so rather than silently producing an
  // orphan unit with no parent. The button is not offered on units; this is the
  // hand-typed-URL path.
  let kind = src.kind;
  if (!CREATABLE.has(kind)) {
    kind = "standalone";
    dropped.push(`its ${src.kind} placement — a ${src.kind} is created from its project`);
  }

  // The party decides `source`, not the other way round: a row carrying a
  // developer is a developer listing whatever else it says.
  const isDeveloper = src.developer_contact_id !== null;

  return {
    fromReference: src.reference,
    source: isDeveloper ? "developer" : "owner",
    partyId: isDeveloper ? src.developer_contact_id : src.owner_contact_id,
    kind,
    propertyType: src.property_type ?? "",
    transactionType: src.transaction_type ?? "sale",
    districtId: src.district_id ?? "",
    areaId: src.area_id ?? "",
    address: src.address ?? "",
    titleEn: (src.title as { en?: string } | null)?.en ?? "",
    askingPrice: str(src.asking_price),
    rentPriceMonth: str(src.rent_price_month),
    plotAreaSqm: str(src.plot_area_sqm),
    coveredAreaSqm: str(src.covered_area_sqm),
    bedrooms: str(src.bedrooms),
    bathrooms: str(src.bathrooms),
    internalNotes: src.internal_notes ?? "",
    dropped,
  };
}
