#!/usr/bin/env node
/**
 * Turn an export from export.mjs into a single SQL file you can read before you
 * run it. See docs/BACKUP_RESTORE.md.
 *
 *   node scripts/backup/restore.mjs --from ../gnk-backups/2026-07-24 > restore.sql
 *   psql "$DB_URL" -v ON_ERROR_STOP=1 -f restore.sql
 *
 * The target must already have the schema (run the migrations first) and must
 * be empty of business rows.
 *
 * Three hazards this handles, each found the hard way during the 2026-07-24
 * drill — see DECISIONS T-backup-drill-run:
 *
 * 1. `session_replication_role = replica` disables FK checks AND user triggers.
 *    Without it, `trg_events_hash` fires on every inserted event and RECOMPUTES
 *    prev_hash/hash from the new row order. The chain would still "verify" —
 *    against freshly minted hashes — so a corrupted restore would look perfect.
 *    That single line is the difference between restoring evidence and
 *    manufacturing it.
 * 2. `events.id` is GENERATED ALWAYS AS IDENTITY, so the insert needs
 *    OVERRIDING SYSTEM VALUE or Postgres silently renumbers the rows — which
 *    breaks the chain, because verify_events_chain walks in id order.
 * 3. Identity/serial sequences must be advanced past the restored maximum, or
 *    the first write after a restore collides on the primary key.
 */
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const args = process.argv.slice(2);
const from = args[args.indexOf("--from") + 1];
if (!from) {
  console.error("usage: restore.mjs --from <backup-dir>");
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(join(from, "manifest.json"), "utf8"));
const TAG = "gnkrestore";

const out = [];
out.push("-- generated by scripts/backup/restore.mjs");
out.push(`-- source: ${manifest.source}`);
out.push(`-- taken:  ${manifest.takenAt}`);
out.push("begin;");
out.push("");
out.push("-- The restore must run in UTC: events.hash covers occurred_at::text,");
out.push("-- which renders through the session TimeZone (BACKUP_RESTORE §1.3).");
out.push("set local timezone = 'UTC';");
out.push("");
out.push("-- Disables FK checks AND user triggers for this transaction — notably");
out.push("-- trg_events_hash, which would otherwise recompute every restored hash.");
out.push("set local session_replication_role = replica;");
out.push("");

for (const table of Object.keys(manifest.tables)) {
  const file = join(from, "data", `${table}.json`);
  if (!existsSync(file)) continue;
  const raw = readFileSync(file, "utf8");
  if (raw === "[]") {
    out.push(`-- ${table}: empty`);
    continue;
  }
  if (raw.includes(`$${TAG}$`)) {
    throw new Error(`${table}: data collides with the dollar-quote tag`);
  }
  out.push(`-- ${table}: ${manifest.tables[table]} rows`);
  // The column list is built from the catalog at RESTORE time rather than
  // hardcoded, so it cannot drift from the schema. Generated-stored columns are
  // excluded: `contacts.display_name` is one, and Postgres rejects any explicit
  // value for it ("cannot insert a non-DEFAULT value"). OVERRIDING SYSTEM VALUE
  // is still needed for identity columns such as events.id, which is a separate
  // thing from a generated column.
  out.push(`create temp table _load (j json) on commit drop;`);
  out.push(`insert into _load values ($${TAG}$${raw}$${TAG}$::json);`);
  out.push(`do $do$
declare cols text;
begin
  select string_agg(quote_ident(attname), ', ' order by attnum) into cols
  from pg_attribute
  where attrelid = 'public.${table}'::regclass
    and attnum > 0 and not attisdropped and attgenerated = '';
  execute format(
    'insert into public.${table} (%s) overriding system value select %s from json_populate_recordset(null::public.${table}, (select j from _load))',
    cols, cols);
end $do$;`);
  out.push(`drop table _load;`);
  out.push("");
}

out.push("-- Advance every identity/serial sequence past what was restored, so the");
out.push("-- first write after a restore does not collide on the primary key.");
out.push(`do $$
declare r record;
begin
  for r in
    select s.relname as seq, t.relname as tbl, a.attname as col
    from pg_class s
    join pg_depend d on d.objid = s.oid and d.classid = 'pg_class'::regclass
    join pg_class t on t.oid = d.refobjid
    join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
    join pg_namespace n on n.oid = t.relnamespace
    where s.relkind = 'S' and n.nspname = 'public'
  loop
    execute format(
      'select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)',
      'public.' || r.seq, r.col, r.tbl);
  end loop;
end $$;`);
out.push("");
out.push("commit;");
out.push("");
out.push("-- Then run scripts/backup/verify-restore.sql against this database.");

process.stdout.write(out.join("\n"));
