-- verify-restore.sql — post-restore verification pack
-- See docs/BACKUP_RESTORE.md §4 step 5 and §5.
--
-- Run against the RESTORED project. Every row must read pass = true.
-- Read-only: it asserts, it never writes.
--
-- REGENERATED 2026-08-30 (audit REL-04). The previous pack had drifted ~25
-- migrations behind the schema: it checked 3 of 8 cron jobs, pinned a
-- 13-function grants table frozen before 0024, and its table list predated
-- share links, reservations, buyer requirements and the chain checkpoint —
-- so a restore could verify GREEN while missing five cron jobs and while
-- anon held default-ACL EXECUTE on every function added since (the hosted
-- false-pass mechanism proven in §6b). The grants table below was NOT typed
-- from memory: it was generated by querying a migration-built local database
-- (all 73 migrations applied), which is the same construction CI proves on
-- every push. When migrations change grants, REGENERATE rather than editing
-- by hand — the query is in the comment above the table.
--
-- The output has THREE kinds of check, and the difference matters when you
-- are reading it under pressure:
--
--   invariant  — true of a correct restore regardless of how much data exists:
--                the event chain, the function grants (the TEST-2 surface),
--                cron, bucket visibility, migration history, session timezone.
--                A failure here is REAL.
--   metadata   — rows agreeing with rows. Cannot see bucket contents, so it
--                CANNOT prove a file survived. Green here is not evidence.
--   row count  — compared against the `expected` block below, which is a
--                SNAPSHOT. If production moved on since it was captured, these
--                fail while the restore is perfectly fine.
--
-- So: **re-capture the baseline immediately before a drill** by running
-- scripts/backup/capture-baseline.sql against the SOURCE and pasting its single
-- output row over the `expected` block. Hardcoded counts previously went stale
-- and reported false failures, which is the worst possible signal mid-recovery.
--
-- (`check` is a reserved word in Postgres, hence `check_name`.)

with expected as (
  -- BASELINE — replace via scripts/backup/capture-baseline.sql before a drill.
  select
    1::bigint as orgs,      2::bigint as profiles,   130::bigint as events,
    2::bigint as contacts,  1::bigint as properties, 1::bigint as deals,
    3::bigint as leads,     0::bigint as viewings,   0::bigint as slips,
    0::bigint as documents, 1::bigint as keys,       1::bigint as mandates,
    0::bigint as tasks,     8::bigint as cyprus_config,
    26::bigint as deal_stages, 5::bigint as districts,
    2::bigint as auth_users, 140::bigint as migrations,
    1::bigint as obj_documents, 0::bigint as obj_signatures, 0::bigint as obj_media,
    2::bigint as share_links, 2::bigint as share_link_properties,
    0::bigint as unit_types, 0::bigint as buyer_requirements,
    0::bigint as reservations, 0::bigint as reservation_installments,
    14::bigint as task_kinds, 1::bigint as chain_checkpoints
    -- captured 2026-08-30 from hosted (yjgirvzgoiywdojnpkpd) via
    -- capture-baseline.sql, after the 08-29/30 audit-fix run (0070–0073,
    -- PAF0001 content fixes, test-photo deletion — which is why media
    -- objects read 0). migrations and task_kinds bumped 2026-08-31 for
    -- 0074–0078 — caught by the cloud drill, §4e — and were STALE AGAIN
    -- within hours when 0079 merged (bumped to 79 on 2026-09-01). The pin
    -- is now locked to the migration files by verify-restore.test.ts, so
    -- a migration can no longer land without this line moving. The number
    -- is deliberately NOT repeated in this comment: the test guards the
    -- pin, not the prose, and the prose is where it went stale twice.
    --
    -- KNOWN CLOUD DELTA (verified 2026-08-31, §4e): on ANY cloud project
    -- — live production included — exactly NINE grants rows fail with
    -- service_role EXECUTE = true where this table (built from a local,
    -- migration-built database) says false: mfa_satisfied, org_mfa_status,
    -- protect_document_columns, protect_profile_columns,
    -- rls_bare_auth_calls, trg_events_hash, trg_price_history,
    -- trg_supersede_deal_nudges, trg_supersede_viewing_nudges — plus, since
    -- 0080 pinned them at service=false: set_updated_at and
    -- protect_property_reference, same mechanism, so ELEVEN rows on a cloud
    -- target. DRILL-VERIFIED ON CLOUD 2026-09-05 (previously predicted but
    -- unverified for that pair): a read-only run of this pack against live
    -- production failed exactly these eleven grants rows and no others, so
    -- the prediction held for the 0080 pair too. That is the
    -- platform's default privileges granting service_role EXECUTE on every
    -- function (HANDOFF's mfa_satisfied note, generalized). service_role
    -- bypasses RLS anyway — the delta is harmless. A cloud run of this
    -- pack that fails ONLY those rows has CONVERGED to production's
    -- own posture: the 2026-08-31 drill proved live production fails the
    -- identical set.
    --
    -- `events` IS THE ONE THAT GOES STALE. It is append-only, so it drifts
    -- upward on every single use of the app and never returns. Check `events`
    -- first when this block looks wrong, and re-capture rather than assuming
    -- a bad restore.
    --
    -- The rate-limit counter tables (share_link_attempts,
    -- public_listing_attempts, public_enquiry_attempts) are DELIBERATELY
    -- absent from the counts: they self-prune on a rolling window, so any
    -- snapshot of them is stale by design and would manufacture false
    -- failures. They still travel in export.mjs — whose TABLES list is now
    -- pinned to the migrations by verify-restore.test.ts, after 0084's
    -- counter was missing from it for a day.
),

-- ---------- row counts ----------
counts as (
  select 'rows: organizations' as check_name, e.orgs as expected, (select count(*) from organizations) as actual from expected e
  union all select 'rows: profiles',      e.profiles,      (select count(*) from profiles) from expected e
  union all select 'rows: events',        e.events,        (select count(*) from events) from expected e
  union all select 'rows: contacts',      e.contacts,      (select count(*) from contacts) from expected e
  union all select 'rows: properties',    e.properties,    (select count(*) from properties) from expected e
  union all select 'rows: deals',         e.deals,         (select count(*) from deals) from expected e
  union all select 'rows: leads',         e.leads,         (select count(*) from leads) from expected e
  union all select 'rows: viewings',      e.viewings,      (select count(*) from viewings) from expected e
  union all select 'rows: viewing_slips', e.slips,         (select count(*) from viewing_slips) from expected e
  union all select 'rows: documents',     e.documents,     (select count(*) from documents) from expected e
  union all select 'rows: property_keys', e.keys,          (select count(*) from property_keys) from expected e
  union all select 'rows: mandates',      e.mandates,      (select count(*) from mandates) from expected e
  union all select 'rows: tasks',         e.tasks,         (select count(*) from tasks) from expected e
  union all select 'rows: share_links',   e.share_links,   (select count(*) from share_links) from expected e
  union all select 'rows: share_link_properties', e.share_link_properties, (select count(*) from share_link_properties) from expected e
  union all select 'rows: unit_types',    e.unit_types,    (select count(*) from unit_types) from expected e
  union all select 'rows: buyer_requirements', e.buyer_requirements, (select count(*) from buyer_requirements) from expected e
  union all select 'rows: reservations',  e.reservations,  (select count(*) from reservations) from expected e
  union all select 'rows: reservation_installments', e.reservation_installments, (select count(*) from reservation_installments) from expected e
  union all select 'seed: task_kinds',    e.task_kinds,    (select count(*) from task_kinds) from expected e
  union all select 'rows: events_chain_checkpoint', e.chain_checkpoints, (select count(*) from events_chain_checkpoint) from expected e
  union all select 'seed: cyprus_config', e.cyprus_config, (select count(*) from cyprus_config) from expected e
  union all select 'seed: deal_stages',   e.deal_stages,   (select count(*) from deal_stages) from expected e
  union all select 'seed: districts',     e.districts,     (select count(*) from districts) from expected e
  union all select 'auth: users',         e.auth_users,    (select count(*) from auth.users) from expected e
  union all select 'migrations: rows',    e.migrations,    (select count(*) from supabase_migrations.schema_migrations) from expected e
  union all select 'storage: documents objects',  e.obj_documents,  (select count(*) from storage.objects where bucket_id = 'documents') from expected e
  union all select 'storage: signatures objects', e.obj_signatures, (select count(*) from storage.objects where bucket_id = 'signatures') from expected e
  union all select 'storage: media objects',      e.obj_media,      (select count(*) from storage.objects where bucket_id = 'media') from expected e
),

-- ---------- function grants: the TEST-2 surface ----------
-- A restore that silently drops OR GAINS one of these looks perfectly healthy
-- on screen. GAINS are the likelier accident on hosted: default privileges
-- hand anon EXECUTE on every newly created function (§6b grant probe), so a
-- restore that replays migrations through a path that misses a revoke leaves
-- a sweep or reporting function anon-callable.
--
-- GENERATED 2026-08-30 from a migration-built local DB at 0073 — regenerate,
-- do not hand-edit:
--   select distinct p.proname, p.prosecdef,
--          has_function_privilege('anon', p.oid, 'EXECUTE'),
--          has_function_privilege('authenticated', p.oid, 'EXECUTE'),
--          has_function_privilege('service_role', p.oid, 'EXECUTE')
--     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--    where n.nspname = 'public' and (p.prosecdef or <project fn list>);
grants_expected(fn, secdef, anon, auth, service) as (values
  -- chain of custody
  ('verify_events_chain',      true,  false, false, true),
  ('run_chain_checks',         true,  false, false, true),
  ('run_chain_checks_full',    true,  false, false, true),
  ('advance_chain_checkpoint', true,  false, false, true),
  ('ensure_events_partitions', true,  false, false, true),
  ('events_partition_health',  true,  false, false, true),
  -- sweeps: cron runs them as postgres; nothing else may call them.
  -- expire_mandates: service_role = false since 0022 (undocumented hosted
  -- grants encoded drift; pg_cron needs no grant).
  ('expire_mandates',            true, false, false, false),
  ('create_followup_nudges',     true, false, false, true),
  ('expire_reservations',        true, false, false, true),
  ('warn_expiring_reservations', true, false, false, true),
  ('remind_due_installments',    true, false, false, true),
  ('raise_key_recall_tasks',     true, false, false, true),
  ('redact_stale_enquiries',     true, false, false, true),
  ('nudge_threshold',            true, false, false, true),
  -- RLS helpers and the 2FA gate. mfa_satisfied is pinned to the
  -- MIGRATION-BUILT value; hosted historically carries an extra service_role
  -- EXECUTE (pre-existing, noted at 0059) — if this row ALONE fails against a
  -- hosted-derived target, compare against that note before treating it as a
  -- bad restore.
  ('current_org_id',   true, false, true, false),
  ('current_role_gnk', true, false, true, false),
  ('mfa_satisfied',    true, false, true, false),
  ('org_mfa_status',   true, false, true, false),
  ('rls_aal2_coverage',        true, false, false, true),
  ('rls_bare_auth_calls',      true, false, true,  false),
  ('rls_bare_helper_calls',    true, false, false, true),
  ('rls_hoisted_policy_count', true, false, false, true),
  -- cron visibility (0074): the admin-dashboard health read, service only
  ('cron_health',          true,  false, false, true),
  -- app RPCs
  ('next_reference',       true,  false, true, true),
  ('record_key_movement',  true,  false, true, true),
  ('move_deal_to_stage',   false, false, true, true),
  -- 0117: authenticated ONLY — a close needs an accountable actor.
  -- 0118: SECURITY DEFINER — the one path by which a user session makes a
  -- deal won or lost (deals_closed_guard refuses every other); it restates
  -- deals_update and require_aal2 itself, and service_role still may not call it
  ('close_deal',           true,  false, true, false),
  -- 0141: authenticated ONLY — a price-list version needs an accountable
  -- actor; SECURITY INVOKER, so every policy on the rows it writes still
  -- binds the caller (pinned although invokers are out of grant_unpinned's scope)
  ('record_price_list_version', false, false, true, false),
  ('add_deal_stage',       false, false, true, true),
  ('reorder_stage',        false, false, true, true),
  ('admin_dashboard_stats',false, false, true, true),
  -- reporting engine (0065) — SECURITY INVOKER by design (the MV lesson)
  ('report_agent_performance', false, false, true, true),
  ('report_source_roi',        false, false, true, true),
  ('report_time_to_close',     false, false, true, true),
  ('report_stage_conversion',  false, false, true, true),
  ('report_price_reductions',  false, false, true, true),
  ('report_citation',          false, false, true, true),
  ('published_below_threshold',false, false, true, true),
  -- the deliberate anon surface: share links (0023/0041, + the 0081
  -- read-only budget peek), the public listing feed (0066/0073/0086) and
  -- the portal feed (0095, the three rows below the enquiry door).
  -- anon = TRUE is unique to these NINE rows, and nothing else in the
  -- database — which is the point: a restore that DROPS these grants kills
  -- every live proposal link, the marketing feed and every portal pull
  -- silently, which is why they are pinned. (The count is stated because it
  -- is checkable: grep this file for ^  \('.*true, true, true, true\) — the
  -- row form, so this sentence is not itself a hit — and it must return
  -- nine. It was six from 0088 to 0094; eight from 0084 to 0087, while the
  -- enquiry door was anon-callable.)
  ('resolve_share_link',      true, true, true, true),
  ('share_link_over_budget',  true, true, true, true),
  ('note_share_link_miss',    true, true, true, true),
  ('public_listings',         true, true, true, true),
  ('public_listings_etag',    true, true, true, true),
  ('note_public_listing_hit', true, true, true, true),
  -- the public enquiry door (0084): a WRITE, so since 0087 it is
  -- service_role-only — the Next route is the door and holds the counter,
  -- the honeypot and the alert; anon reaching the function skipped all
  -- three (audit A01). A restore that re-grants anon here re-opens that.
  ('submit_public_enquiry',   true, false, false, true),
  ('note_public_enquiry_hit', true, false, false, true),
  -- the lead SLA sweep (0098): cron runs it as postgres; nobody else may
  ('raise_lead_sla_tasks',    true, false, false, true),
  -- the two-minute desk-alert sweep (0103): an INVOKER body that reads Vault
  -- and posts through pg_net; cron runs it as postgres, service_role may
  -- rehearse it, nobody else may call it. secdef FALSE: this row said true
  -- until 2026-10-01 and read red on every correct restore (0103 / 0105
  -- define it security invoker; measured false on local and hosted).
  ('enquiry_alerts_sweep',    false, false, false, true),
  -- the sweep's outcome record (0105): the reconciler reads pg_net as postgres,
  -- the health read feeds the dashboard, the classifier is pure; all
  -- service_role-only like cron_health
  ('reconcile_enquiry_alert_sweeps',         true,  false, false, true),
  ('enquiry_alert_sweep_health',             true,  false, false, true),
  ('classify_enquiry_alert_sweep_response',  false, false, false, true),
  -- a buyer's interest in one proposal property (0106): the second public
  -- door, service_role-only like the first since 0087
  ('submit_proposal_interest',               true,  false, false, true),
  -- the desk-alert outbox (0101): the worker's two functions are
  -- service_role-only (the sweep route and the enquiry route's after() hold
  -- the service key); the staff retry is authenticated-callable and checks
  -- the org, the lead rule, the lease and the redaction itself.
  ('claim_notification_jobs',     true, false, false, true),
  ('complete_notification_job',   true, false, false, true),
  ('request_enquiry_alert_retry', true, false, true,  true),
  -- the escalation's recovery (0111): authenticated-callable like the desk
  -- alert's retry and stricter — admin only, by job id, every rule in SQL
  ('request_lead_escalation_recovery', true, false, true, true),
  -- the activation preview (0112): authenticated-callable like the recovery
  -- and as strict (admin, aal2, own org); STABLE, so it cannot write. The
  -- one eligibility rule it shares with the sweep is service_role-only.
  ('preview_lead_escalation',        true, false, true, true),
  ('lead_escalation_candidates',     true, false, false, true),
  -- the lead escalation (0107): the policy reader, the working-time clock and
  -- the five-minute minting sweep — cron runs the sweep as postgres,
  -- service_role may rehearse all three, nobody else may call them
  ('lead_escalation_config',      true, false, false, true),
  ('lead_escalation_due_at',      true, false, false, true),
  ('raise_lead_escalations',      true, false, false, true),
  -- the portal feed (0095): a portal PULLS over a tokenised URL, so these
  -- three are anon-callable and the 64-hex token in the URL is the whole
  -- gate — since 0097 the row holds only its sha256, and the functions take
  -- the digest.
  -- note_portal_pull WRITES (the last_pull* columns) and is still anon —
  -- unlike the 0084 door it takes only two harmless caller values (a
  -- user-agent string cut to 200 chars, a count clamped at 0), touches only
  -- the one row named by the token, and the route needs no service key to
  -- record a pull.
  -- portal_supplement is the only place coordinates leave the database.
  ('portal_connection_by_token', true, true, true, true),
  ('portal_supplement',          true, true, true, true),
  ('note_portal_pull',           true, true, true, true),
  -- trigger bodies: callable by nobody over PostgREST (0007/0021)
  ('trg_events_hash',              true, false, false, false),
  -- + the two invoker trigger bodies 0080 brought into the same posture,
  -- pinned to the MIGRATION-BUILT value (on cloud these two join the nine
  -- service_role default-ACL deltas in the KNOWN CLOUD DELTA note above)
  ('set_updated_at',               false, false, false, false),
  ('protect_property_reference',   false, false, false, false),
  ('trg_price_history',            true, false, false, false),
  ('trg_supersede_deal_nudges',    true, false, false, false),
  ('trg_supersede_viewing_nudges', true, false, false, false),
  -- 0117: revoked from all four roles explicitly, so hosted matches local
  ('trg_deals_closed_guard',       false, false, false, false),
  -- 0131: the one writer of a session-time deal stage_changed — a definer
  -- trigger body, revoked from all four roles explicitly like the guard above
  ('trg_deals_stage_changed_event', true, false, false, false),
  -- 0132: a session may not change a primary-key value — an invoker trigger
  -- body on 25 tables, revoked from all four roles explicitly like the guard above
  ('trg_primary_key_immutable',    false, false, false, false),
  -- 0133: a session may not create a row at an id with history — a DEFINER
  -- trigger body (it must see history the session cannot), revoked from all four
  -- roles explicitly like trg_deals_stage_changed_event
  ('trg_insert_id_without_history', true, false, false, false),
  -- 0134: a session may not write a contact's erasure record, change an
  -- erased contact or delete its retained documents — invoker trigger
  -- bodies, revoked from all four roles explicitly like the guards above
  ('trg_contacts_erasure_lifecycle',   false, false, false, false),
  ('trg_documents_kept_for_retention', false, false, false, false),
  -- 0101: erasure cancels a lead's pending desk alert — a trigger body that
  -- even service_role may not call (like the definer trigger bodies above)
  ('cancel_lead_notification_jobs', true, false, false, false),
  ('protect_document_columns',     true, false, false, false),
  ('protect_profile_columns',      true, false, false, false),
  -- 0127: status / holder of a key change only through record_key_movement;
  -- revoked from all four roles explicitly, as 0117's guard
  ('property_keys_movement_fields_guard', false, false, false, false),
  -- 0099's statement trigger guarding PostGIS's spatial_ref_sys from the API
  -- roles. A trigger body cannot be called through /rpc, so the default
  -- EXECUTE grants it carries are inert; pinned as measured on local AND
  -- hosted 2026-10-01 (it was UNPINNED, which failed this pack closed)
  ('forbid_srs_api_writes',       false, true, true, true)
),
grants_actual as (
  select distinct p.proname::text as fn, p.prosecdef as secdef,
         has_function_privilege('anon', p.oid, 'EXECUTE') as anon,
         has_function_privilege('authenticated', p.oid, 'EXECUTE') as auth,
         has_function_privilege('service_role', p.oid, 'EXECUTE') as service
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
),
grant_checks as (
  select 'grants: ' || ge.fn as check_name,
         ge.secdef::text || '/' || ge.anon::text || '/' || ge.auth::text || '/' || ge.service::text as expected,
         coalesce(ga.secdef::text || '/' || ga.anon::text || '/' || ga.auth::text || '/' || ga.service::text, 'FUNCTION MISSING') as actual
  from grants_expected ge left join grants_actual ga on ga.fn = ge.fn
),
-- ---------- the reverse direction: FAIL CLOSED on the unpinned ----------
-- The join above only examines functions somebody remembered to pin — the
-- 2026-09-01 review caught it blind to 0074's cron_health() eleven minutes
-- after the list was generated. Any public SECURITY DEFINER function, or any
-- function anon can execute, that is NOT in grants_expected fails here: the
-- two classes where a silently-unchecked function is a hole, not a nit.
-- (authenticated-EXECUTE invoker functions are deliberately out of scope —
-- that is the default posture for app RPCs and would drown the signal.)
grant_unpinned as (
  select distinct 'grants: UNPINNED ' || p.proname as check_name,
         'pinned in grants_expected' as expected,
         'secdef=' || p.prosecdef::text
           || ' anon=' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
           || ' — add the row (regenerate the list) before trusting this pack' as actual
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and (p.prosecdef or has_function_privilege('anon', p.oid, 'EXECUTE'))
    and not exists (select 1 from grants_expected ge where ge.fn = p.proname)
    -- extension-owned functions (PostGIS ships hundreds, anon-executable by
    -- design) are the platform's surface, not this schema's — out of scope
    and not exists (select 1 from pg_depend d
                    where d.classid = 'pg_proc'::regclass and d.objid = p.oid
                      and d.refclassid = 'pg_extension'::regclass and d.deptype = 'e')
),

-- ---------- everything else ----------
misc as (
  select 'timezone is UTC (see BACKUP_RESTORE 1.3)' as check_name,
         'UTC' as expected, current_setting('TimeZone') as actual
  union all
  select 'migrations: non_filename_versions', '0',
         (select count(*)::text from supabase_migrations.schema_migrations where version !~ '^[0-9]{4}$')
  union all
  -- ALL TWELVE cron jobs (the previous pack checked three, so a restore that
  -- lost the other five verified green — audit REL-04; the ninth is 0092's
  -- retention sweep, the tenth 0098's ten-minute lead SLA, the eleventh 0103's
  -- two-minute desk-alert sweep through pg_net, the twelfth 0107's five-minute
  -- lead escalation). pg_cron jobs are in
  -- NO dump; after a restore every one must be recreated from the migrations
  -- (§4b.4), and this is the list that proves it happened.
  select 'cron: ' || j.jobname || ' active', 'true',
         coalesce((select active::text from cron.job where jobname = j.jobname), 'JOB MISSING')
  from (values ('expire-mandates'), ('followup-nudges'), ('verify-events-chain'),
               ('verify-events-chain-full'), ('expire-reservations'),
               ('warn-expiring-reservations'), ('remind-due-installments'),
               ('ensure-events-partitions'), ('redact-stale-enquiries'),
               ('lead-sla'), ('enquiry-alerts'), ('lead-escalation')) as j(jobname)
  union all
  select 'cron: exactly 12 jobs, none extra', '12',
         (select count(*)::text from cron.job)
  union all
  -- 0103: the enquiry-alerts job reads these two at run time and FAILS
  -- without them. Vault rows survive a same-project restore; a restore into
  -- a NEW project cannot decrypt them (the key is the project's) and they
  -- must be recreated by hand (docs/10 §2) — this line proves it happened.
  select 'vault: crm_url + cron_secret present (0103)', 'true',
         (exists (select 1 from vault.decrypted_secrets where name = 'crm_url')
          and exists (select 1 from vault.decrypted_secrets where name = 'cron_secret'))::text
  union all
  select 'storage: media bucket is public (migration 0008)', 'true',
         coalesce((select public::text from storage.buckets where id = 'media'), 'BUCKET MISSING')
  union all
  select 'storage: documents bucket is private', 'false',
         coalesce((select public::text from storage.buckets where id = 'documents'), 'BUCKET MISSING')
  union all
  select 'storage: signatures bucket is private', 'false',
         coalesce((select public::text from storage.buckets where id = 'signatures'), 'BUCKET MISSING')
  union all
  -- events partitions must live OUTSIDE public (0063): pg_default_acl grants
  -- anon TRUNCATE-bearing rights on anything created in public, and RLS does
  -- not gate TRUNCATE. A restore that recreated them in public is exposed.
  select 'partitions: all events partitions in events_parts schema', '0',
         (select count(*)::text
            from pg_inherits i
            join pg_class c on c.oid = i.inhrelid
            join pg_namespace n on n.oid = c.relnamespace
           where i.inhparent = 'public.events'::regclass
             and n.nspname <> 'events_parts')
  union all
  select 'partitions: events_partition_health() is empty', '0',
         (select count(*)::text from events_partition_health())
  union all
  -- The one that matters most. False here means re-read §1.3 BEFORE assuming corruption:
  -- a non-UTC session TimeZone breaks verification on perfectly intact data.
  select 'INTEGRITY: event chain verifies for every org', 'true',
         (select coalesce(bool_and(verify_events_chain(id)), true)::text from organizations)
  union all
  -- 0119: a task names a deal of its OWN organisation, or none. The composite
  -- key guarantees it for every live write, but a replica-mode restore
  -- (restore.mjs, data.sql) loads rows past every constraint and leaves the
  -- key marked validated — this is the check the catalogue flag cannot give.
  -- Non-zero means the SOURCE held mismatches (0119's preflight refuses to
  -- constrain over them; the sweep's steps 1/3 would then act across
  -- organisations — BACKLOG NOTE).
  select 'INTEGRITY: no task names a deal of another organisation (0119)', '0',
         (select count(*)::text from tasks t join deals d on d.id = t.deal_id where t.org_id <> d.org_id)
  union all
  -- 0120: the viewing twin — same reason, a replica-mode restore loads rows
  -- past tasks_org_viewing_fkey and leaves it marked validated.
  select 'INTEGRITY: no task names a viewing of another organisation (0120)', '0',
         (select count(*)::text from tasks t join viewings v on v.id = t.viewing_id where t.org_id <> v.org_id)
  union all
  -- 0121: the mandate twin — same reason; here a mismatch would also let the
  -- key-recall and renewal sweeps' guards read across organisations only if
  -- their 0121 predicates were ever lost, so the row is the data half of that
  -- defence.
  select 'INTEGRITY: no task names a mandate of another organisation (0121)', '0',
         (select count(*)::text from tasks t join mandates m on m.id = t.mandate_id where t.org_id <> m.org_id)
  union all
  -- 0122: a mandate's property and predecessor, and a key's property, are of
  -- its own organisation — same reason as the rows above: a replica-mode
  -- restore loads rows past the keys and leaves them marked validated.
  select 'INTEGRITY: no mandate names a property of another organisation (0122)', '0',
         (select count(*)::text from mandates m join properties p on p.id = m.property_id where m.org_id <> p.org_id)
  union all
  select 'INTEGRITY: no key opens a property of another organisation (0122)', '0',
         (select count(*)::text from property_keys k join properties p on p.id = k.property_id where k.org_id <> p.org_id)
  union all
  select 'INTEGRITY: no mandate renews a mandate of another organisation (0122)', '0',
         (select count(*)::text from mandates m join mandates r on r.id = m.renewed_from_id where m.org_id <> r.org_id)
  union all
  -- 0123: a viewing's property and contact are of its own organisation — same
  -- reason as the rows above; here a mismatch is also what the nightly sweep's
  -- viewing arms would otherwise read across organisations.
  select 'INTEGRITY: no viewing names a property of another organisation (0123)', '0',
         (select count(*)::text from viewings v join properties p on p.id = v.property_id where v.org_id <> p.org_id)
  union all
  select 'INTEGRITY: no viewing names a contact of another organisation (0123)', '0',
         (select count(*)::text from viewings v join contacts c on c.id = v.contact_id where v.org_id <> c.org_id)
  union all
  -- 0124: a reservation's property, an instalment line's reservation and a
  -- lead's property are of its own organisation — same reason as the rows
  -- above; a mismatch is also what the reservation, instalment and lead-SLA
  -- sweeps would otherwise read across organisations.
  select 'INTEGRITY: no reservation holds a property of another organisation (0124)', '0',
         (select count(*)::text from reservations r join properties p on p.id = r.property_id where r.org_id <> p.org_id)
  union all
  select 'INTEGRITY: no instalment line belongs to a reservation of another organisation (0124)', '0',
         (select count(*)::text from reservation_installments i join reservations r on r.id = i.reservation_id where i.org_id <> r.org_id)
  union all
  select 'INTEGRITY: no lead names a property of another organisation (0124)', '0',
         (select count(*)::text from leads l join properties p on p.id = l.property_id where l.org_id <> p.org_id)
  union all
  -- 0125: a task's reservation, instalment line and lead are of its own
  -- organisation — same reason as the rows above; a mismatch is also what the
  -- four sweeps' guards and self-heals would read across organisations if
  -- their 0125 predicates were ever lost.
  select 'INTEGRITY: no task names a reservation of another organisation (0125)', '0',
         (select count(*)::text from tasks t join reservations r on r.id = t.reservation_id where t.org_id <> r.org_id)
  union all
  select 'INTEGRITY: no task names an instalment line of another organisation (0125)', '0',
         (select count(*)::text from tasks t join reservation_installments i on i.id = t.installment_id where t.org_id <> i.org_id)
  union all
  select 'INTEGRITY: no task names a lead of another organisation (0125)', '0',
         (select count(*)::text from tasks t join leads l on l.id = t.lead_id where t.org_id <> l.org_id)
  union all
  -- 0125: and none names one that does not exist. A row that escaped the
  -- composite keys is not cascaded by its parent's delete (its (org_id, id)
  -- pair matches no parent), and a replica-mode restore loads a dangling id
  -- past the key as readily as a foreign one; the joins above cannot see either.
  select 'INTEGRITY: no task names a reservation, instalment line or lead that does not exist (0125)', '0',
         (select count(*)::text from tasks t
           where (t.reservation_id is not null and not exists (select 1 from reservations r where r.id = t.reservation_id))
              or (t.installment_id is not null and not exists (select 1 from reservation_installments i where i.id = t.installment_id))
              or (t.lead_id is not null and not exists (select 1 from leads l where l.id = t.lead_id)))
  union all
  -- 0126: a reservation's contact, and a task's contact and property, are of
  -- its own organisation — same reason as the rows above; a mismatch is also
  -- what the retention sweep's guard and self-heal (and, for a hold, the two
  -- reservation sweeps' contact copy) would read across organisations if
  -- their 0126 predicates were ever lost.
  select 'INTEGRITY: no reservation names a contact of another organisation (0126)', '0',
         (select count(*)::text from reservations r join contacts c on c.id = r.contact_id where r.org_id <> c.org_id)
  union all
  select 'INTEGRITY: no task names a contact of another organisation (0126)', '0',
         (select count(*)::text from tasks t join contacts c on c.id = t.contact_id where t.org_id <> c.org_id)
  union all
  select 'INTEGRITY: no task names a property of another organisation (0126)', '0',
         (select count(*)::text from tasks t join properties p on p.id = t.property_id where t.org_id <> p.org_id)
  union all
  -- 0126: and none names one that does not exist — 0125's reason: a row that
  -- escaped the composite keys is neither cleared (SET NULL) nor refused by
  -- its parent's delete, and a replica-mode restore loads a dangling id past
  -- the key; the joins above cannot see either.
  select 'INTEGRITY: no reservation or task names a contact or property that does not exist (0126)', '0',
         (select count(*)::text from (
             select 1 from reservations r where r.contact_id is not null and not exists (select 1 from contacts c where c.id = r.contact_id)
           union all
             select 1 from tasks t
              where (t.contact_id is not null and not exists (select 1 from contacts c where c.id = t.contact_id))
                 or (t.property_id is not null and not exists (select 1 from properties p where p.id = t.property_id))) x)
  union all
  -- 0127: the definer surfaces a signed-in session reaches check the second
  -- factor, and the key tables are written only through record_key_movement.
  -- A restore that brought back an older schema would read aal1 through them.
  select 'SECURITY: the 0127 definer surfaces check the second factor (3 functions + mandates_safe)', '4',
         ((select count(*) from pg_proc p
            where p.pronamespace = 'public'::regnamespace
              and p.proname in ('record_key_movement', 'next_reference', 'org_mfa_status')
              and regexp_replace(regexp_replace(regexp_replace(p.prosrc, '/\*.*?\*/', '', 'g'), '--[^\n]*', '', 'g'), '''([^'']|'''')*''', '', 'g') ~ '\mmfa_satisfied\s*\(')
          + (pg_get_viewdef('public.mandates_safe'::regclass) ~ 'mfa_satisfied\(')::int)::text
  union all
  select 'SECURITY: key movements only through the RPC — no INSERT policy, the guard trigger enabled (0127)', '0 1',
         (select count(*) from pg_policy where polrelid = 'public.key_movements'::regclass and polcmd = 'a')::text || ' ' ||
         (select count(*) from pg_trigger where tgrelid = 'public.property_keys'::regclass
             and tgname = 'property_keys_movement_fields_guard' and tgenabled = 'O')::text
  union all
  -- 0128: a session may not write a deal's terminal event (only close_deal, a
  -- definer, does) nor choose an event's occurred_at. A restore that brought
  -- back an older events_insert would read false here.
  -- coalesce: a restore with NO events_insert must read false, not NULL (a
  -- NULL pass sorts below the passing rows)
  select 'SECURITY: events_insert refuses a session''s terminal deal event and a chosen occurred_at (0128)', 'true',
         coalesce((select (pg_get_expr(p.polwithcheck, p.polrelid) ~ 'won_override'
                           and pg_get_expr(p.polwithcheck, p.polrelid) ~ 'occurred_at = now\(\)')::text
                     from pg_policy p
                    where p.polrelid = 'public.events'::regclass and p.polname = 'events_insert'), 'false')
  union all
  -- 0129: a deal's offers, holds, viewings and converted lead are of the
  -- deal's organisation, a hold's offer of the hold's, a viewing's signed
  -- slip of the viewing's — same reason as the rows above (a replica-mode
  -- restore loads a foreign link past the keys as readily as a valid one).
  -- One row for the six links: each count is named, so a red row says which.
  select 'INTEGRITY: no offer, hold, viewing, converted lead or slip names a deal / offer / viewing of another organisation (0129)',
         'offers 0, holds-deal 0, holds-offer 0, viewings 0, leads 0, slips 0',
         format('offers %s, holds-deal %s, holds-offer %s, viewings %s, leads %s, slips %s',
           (select count(*) from offers o        join deals d    on d.id = o.deal_id           where o.org_id <> d.org_id),
           (select count(*) from reservations r  join deals d    on d.id = r.deal_id           where r.org_id <> d.org_id),
           (select count(*) from reservations r  join offers x   on x.id = r.offer_id          where r.org_id <> x.org_id),
           (select count(*) from viewings v      join deals d    on d.id = v.deal_id           where v.org_id <> d.org_id),
           (select count(*) from leads l         join deals d    on d.id = l.converted_deal_id where l.org_id <> d.org_id),
           (select count(*) from viewing_slips s join viewings v on v.id = s.viewing_id        where s.org_id <> v.org_id))
  union all
  -- 0129: and none names one that does not exist — 0125's reason: a row that
  -- escaped the composite keys is neither cascaded nor cleared by its
  -- parent's delete, and a replica-mode restore loads a dangling id past the
  -- key; the joins above cannot see either.
  select 'INTEGRITY: no offer, hold, viewing, converted lead or slip names a deal / offer / viewing that does not exist (0129)', '0',
         (select count(*)::text from (
             select 1 from offers o where not exists (select 1 from deals d where d.id = o.deal_id)
           union all
             select 1 from reservations r
              where (r.deal_id is not null and not exists (select 1 from deals d where d.id = r.deal_id))
                 or (r.offer_id is not null and not exists (select 1 from offers x where x.id = r.offer_id))
           union all
             select 1 from viewings v where v.deal_id is not null and not exists (select 1 from deals d where d.id = v.deal_id)
           union all
             select 1 from leads l where l.converted_deal_id is not null and not exists (select 1 from deals d where d.id = l.converted_deal_id)
           union all
             select 1 from viewing_slips s where not exists (select 1 from viewings v where v.id = s.viewing_id)) x)
  union all
  -- 0130: report_stage_conversion classifies each stage id before casting it,
  -- so one malformed stage_changed payload is excluded and counted instead of
  -- failing every report window that contains it. A restore that brought back
  -- 0076's body would read false here (its two casts are unguarded nullif ones).
  select 'HONESTY: report_stage_conversion guards its uuid casts and counts malformed moves (0130)', 'true',
         coalesce((select (p.prosrc ~ 'pg_input_is_valid\(' and p.prosrc ~ 'moves_malformed'
                           and p.prosrc !~ 'nullif\(e\.payload')::text
                     from pg_proc p
                    where p.oid = to_regprocedure('public.report_stage_conversion(timestamptz, timestamptz)')), 'false')
  union all
  -- 0131: a deal's stage_changed is written from the row change by the
  -- deals_stage_changed_event trigger, never by a session: events_insert
  -- refuses a session's, the trigger is enabled, and move_deal_to_stage no
  -- longer inserts its own (with the trigger, that would be two per move). A
  -- restore that brought back 0128's policy, lost the trigger or 0067's RPC
  -- body reads false here.
  select 'SECURITY: a deal''s stage_changed comes only from its stage change — events_insert refuses a session''s, the trigger writes it (0131)', 'true',
         (coalesce((select pg_get_expr(p.polwithcheck, p.polrelid) ~ '\(event_type <> ''stage_changed''::text\)'
                      from pg_policy p
                     where p.polrelid = 'public.events'::regclass and p.polname = 'events_insert'), false)
          and exists (select 1 from pg_trigger t
                       where t.tgrelid = 'public.deals'::regclass and t.tgname = 'deals_stage_changed_event'
                         and t.tgenabled = 'O'
                         and t.tgfoid = to_regprocedure('public.trg_deals_stage_changed_event()'))
          and coalesce((select regexp_replace(p.prosrc, '--[^\n]*', '', 'g') !~* 'insert\s+into\s+(public\.)?events'
                          from pg_proc p
                         where p.oid = to_regprocedure('public.move_deal_to_stage(uuid, uuid)')), false))::text
  union all
  -- 0132: a session may not change a record's primary key. Every public table
  -- (not extension-owned) where an API role may UPDATE a key column carries a
  -- trg_primary_key_immutable trigger of the guard's exact shape (enabled, no
  -- WHEN, BEFORE / ROW / UPDATE OF exactly the key, the key as its arguments) —
  -- deals excepted: its 0131 guard refuses — 25 enabled guards exist, and the
  -- function still binds sessions with 42501. Default privileges differ by
  -- environment (hosted grants anon / authenticated arwdDxtm on every new
  -- public table, the pinned CLI does not), so run against HOSTED this row is
  -- the one check that reads a new table left session-updatable. A restore
  -- that brought back an older schema, a disabled or misshapen guard, or a
  -- re-opened table reads something else here.
  select 'SECURITY: no session can change a record''s primary key — unguarded tables, guards, session binding (0132)', '0 25 true',
         (select count(*)
            from pg_class c
            join pg_constraint con on con.conrelid = c.oid and con.contype = 'p'
           where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and not c.relispartition
             and c.relname <> 'deals'
             and not exists (select 1 from pg_depend d
                              where d.classid = 'pg_class'::regclass and d.objid = c.oid
                                and d.refclassid = 'pg_extension'::regclass and d.deptype = 'e')
             and exists (select 1 from unnest(con.conkey) k(attnum)
                          where has_column_privilege('authenticated', c.oid, k.attnum, 'UPDATE')
                             or has_column_privilege('anon', c.oid, k.attnum, 'UPDATE'))
             and not exists (
               select 1 from pg_trigger t
                where t.tgrelid = c.oid
                  and t.tgfoid = to_regprocedure('public.trg_primary_key_immutable()')
                  and not t.tgisinternal and t.tgenabled = 'O' and t.tgqual is null
                  and (t.tgtype & 2) = 2 and (t.tgtype & 1) = 1 and (t.tgtype & 16) = 16 and (t.tgtype & (4 | 8 | 32)) = 0
                  and coalesce((select array_agg(x order by x) from unnest(t.tgattr::int2[]) x), '{}')
                      = (select array_agg(x order by x) from unnest(con.conkey) x)
                  and t.tgnargs = cardinality(con.conkey)
                  and (string_to_array(encode(t.tgargs, 'escape'), '\000'))[1:t.tgnargs]
                      = array(select a.attname::text from unnest(con.conkey) with ordinality k(attnum, ord)
                               join pg_attribute a on a.attrelid = t.tgrelid and a.attnum = k.attnum order by k.ord)))::text || ' ' ||
         (select count(*) from pg_trigger t
           where t.tgfoid = to_regprocedure('public.trg_primary_key_immutable()') and t.tgenabled = 'O'
             and not t.tgisinternal)::text || ' ' ||
         coalesce((select not p.prosecdef
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'current_user not in \(''authenticated'', ''anon''\)'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'errcode = ''42501'''
                     from pg_proc p
                    where p.oid = to_regprocedure('public.trg_primary_key_immutable()')), false)::text
  union all
  -- 0133: a session may not create a record at an id that already has
  -- history. The 11 history subjects carry an enabled AFTER INSERT row trigger
  -- of trg_insert_id_without_history with their entity_type as its argument,
  -- and the function is a definer that binds sessions by the role GUC and
  -- refuses with 42501. A restore that lost a trigger, its argument or the
  -- function's session binding reads something else here.
  select 'SECURITY: no session can create a record at an id that already has history — guards, session binding (0133)', '11 true',
         (select count(*)
            from (values ('profiles', 'user'), ('contacts', 'contact'), ('properties', 'property'), ('property_keys', 'key'),
                         ('mandates', 'mandate'), ('leads', 'lead'), ('deals', 'deal'), ('viewings', 'viewing'),
                         ('offers', 'offer'), ('share_links', 'share_link'), ('tasks', 'task')) x(tbl, entity_type)
           where exists (select 1 from pg_trigger t
                          where t.tgrelid = to_regclass('public.' || x.tbl)
                            and t.tgfoid = to_regprocedure('public.trg_insert_id_without_history()')
                            and t.tgname = x.tbl || '_id_without_history'
                            and not t.tgisinternal and t.tgenabled = 'O' and t.tgqual is null
                            and (t.tgtype & (2 | 64)) = 0 and (t.tgtype & 1) = 1 and (t.tgtype & 4) = 4
                            and (t.tgtype & (8 | 16 | 32)) = 0 and t.tgnargs = 1
                            and (string_to_array(encode(t.tgargs, 'escape'), '\000'))[1] = x.entity_type))::text || ' ' ||
         coalesce((select p.prosecdef
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'current_setting\(''role'', true\)'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') !~ 'current_user'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'errcode = ''42501'''
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'public\.events e'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'public\.interaction_notes n'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'public\.documents d'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'e\.actor_id = new\.id'
                     from pg_proc p
                    where p.oid = to_regprocedure('public.trg_insert_id_without_history()')), false)::text
  union all
  -- 0134: an erased contact stays erased. A session (authenticated / anon)
  -- may not insert or change a contact's erased_at / erased_by /
  -- retention_until, nor change an erased contact other than archiving it —
  -- contacts_retain_erasure, an enabled BEFORE INSERT OR UPDATE row trigger
  -- calling the invoker guard — nor delete an erased contact's documents
  -- (documents_kept_for_retention, BEFORE DELETE), and events_insert refuses
  -- a session's `erased` / `retention_purged`, the records the erasure and
  -- the purge write as the system. A restore that brought back 0131's
  -- policy, lost or disabled a trigger, or a guard that binds no session
  -- reads false here.
  select 'SECURITY: an erased contact stays erased — the contacts and documents guards bind sessions, events_insert refuses their erased / retention_purged (0134)', 'true',
         (coalesce((select pg_get_expr(p.polwithcheck, p.polrelid) ~ '\(event_type <> ALL \(ARRAY\[''erased''::text, ''retention_purged''::text\]\)\)'
                      from pg_policy p
                     where p.polrelid = 'public.events'::regclass and p.polname = 'events_insert'), false)
          and exists (select 1 from pg_trigger t
                       where t.tgrelid = 'public.contacts'::regclass and t.tgname = 'contacts_retain_erasure'
                         and t.tgfoid = to_regprocedure('public.trg_contacts_erasure_lifecycle()')
                         and not t.tgisinternal and t.tgenabled = 'O' and t.tgqual is null
                         and (t.tgtype & 2) = 2 and (t.tgtype & 1) = 1 and (t.tgtype & 4) = 4 and (t.tgtype & 16) = 16
                         and (t.tgtype & (8 | 32)) = 0 and cardinality(t.tgattr::int2[]) = 0)
          and coalesce((select not p.prosecdef
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'current_user not in \(''authenticated'', ''anon''\)'
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'old\.erased_at is not null'
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'errcode = ''42501'''
                          from pg_proc p
                         where p.oid = to_regprocedure('public.trg_contacts_erasure_lifecycle()')), false)
          and exists (select 1 from pg_trigger t
                       where t.tgrelid = 'public.documents'::regclass and t.tgname = 'documents_kept_for_retention'
                         and t.tgfoid = to_regprocedure('public.trg_documents_kept_for_retention()')
                         and not t.tgisinternal and t.tgenabled = 'O' and t.tgqual is null
                         and (t.tgtype & 2) = 2 and (t.tgtype & 1) = 1 and (t.tgtype & 8) = 8
                         and (t.tgtype & (4 | 16 | 32)) = 0)
          and coalesce((select not p.prosecdef
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'current_user not in \(''authenticated'', ''anon''\)'
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'c\.erased_at is not null'
                               and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'errcode = ''42501'''
                          from pg_proc p
                         where p.oid = to_regprocedure('public.trg_documents_kept_for_retention()')), false))::text
  union all
  -- 0135: the nightly enquiry sweep (redact_stale_enquiries, cron) blanks only
  -- the notes of the lead it redacted, in that lead's own organisation — notes
  -- outlive their lead and another organisation may hold a lead at its id. A
  -- restore that brought back 0094's body (notes matched by id alone) reads
  -- false here.
  select 'SECURITY: the enquiry sweep blanks only the redacted lead''s own organisation''s notes (0135)', 'true',
         coalesce((select p.prosecdef
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'n\.entity_id = done\.id\s+and n\.org_id = done\.org_id'
                     from pg_proc p
                    where p.oid = to_regprocedure('public.redact_stale_enquiries(integer)')), false)::text
  union all
  -- 0136: the website enquiry door's round-robin (submit_public_enquiry) counts
  -- only its own organisation's open leads and `assigned` events — another
  -- organisation's writes naming our agents must not steer it. A restore that
  -- brought back 0114's body reads false here.
  select 'SECURITY: the website enquiry''s round-robin counts only its own organisation (0136)', 'true',
         coalesce((select p.prosecdef
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'from leads l\s+where l\.org_id = v_org_id\s+and l\.assigned_agent_id = p\.id'
                          and regexp_replace(p.prosrc, '--[^\n]*', '', 'g') ~ 'from events e\s+where e\.org_id = v_org_id\s+and e\.entity_type = ''lead'''
                     from pg_proc p
                    where p.oid = to_regprocedure('public.submit_public_enquiry(text, text, text, text, text, text, text, jsonb)')), false)::text
  union all
  -- 0137: the public share page (resolve_share_link) writes its once-a-day
  -- `opened` line unless THIS organisation's own system line (a null actor)
  -- already exists today — another organisation's or a session's event no
  -- longer suppresses it. A restore that brought back 0041's body reads false.
  select 'SECURITY: a share link''s `opened` throttle counts only its own organisation''s system line (0137)', 'true',
         coalesce((select p.prosecdef
                          and regexp_count(regexp_replace(p.prosrc, '--[^\n]*', '', 'g'),
                                'event_type\s+=\s+''opened''\s+and org_id\s+=\s+v_link\.org_id\s+and actor_id\s+is null') = 2
                     from pg_proc p
                    where p.oid = to_regprocedure('public.resolve_share_link(text)')), false)::text
  union all
  -- 0138: a session may not write the system's enquiry_alert / lead_escalation
  -- / opened events under any entity_type (the claim closes a desk alert on an
  -- enquiry_alert 'sent'; an opened line reads as a buyer's view). A restore
  -- that brought back 0134's events_insert reads false here.
  select 'SECURITY: a session cannot write the system''s enquiry_alert / lead_escalation / opened (0138)', 'true',
         coalesce((select pg_get_expr(p.polwithcheck, p.polrelid) ~ '\(event_type <> ALL \(ARRAY\[''enquiry_alert''::text, ''lead_escalation''::text, ''opened''::text\]\)\)'
                     from pg_policy p
                    where p.polrelid = 'public.events'::regclass and p.polname = 'events_insert'), false)::text
  union all
  -- 0139: every link onto a contact is of the contact's organisation — the
  -- same reason as 0129's rows (a replica-mode restore loads a foreign link
  -- past the keys as readily as a valid one). One row for the ten links; each
  -- count is named, so a red row says which.
  select 'INTEGRITY: no lead, deal, offer, share link, requirement, mandate, listing or merge pointer names a contact of another organisation (0139)',
         'leads 0, deal-buyers 0, deal-sellers 0, offers 0, share-links 0, requirements 0, mandates 0, owners 0, developers 0, merges 0',
         format('leads %s, deal-buyers %s, deal-sellers %s, offers %s, share-links %s, requirements %s, mandates %s, owners %s, developers %s, merges %s',
           (select count(*) from leads x              join contacts c on c.id = x.contact_id           where x.org_id <> c.org_id),
           (select count(*) from deals x              join contacts c on c.id = x.buyer_contact_id     where x.org_id <> c.org_id),
           (select count(*) from deals x              join contacts c on c.id = x.seller_contact_id    where x.org_id <> c.org_id),
           (select count(*) from offers x             join contacts c on c.id = x.contact_id           where x.org_id <> c.org_id),
           (select count(*) from share_links x        join contacts c on c.id = x.contact_id           where x.org_id <> c.org_id),
           (select count(*) from buyer_requirements x join contacts c on c.id = x.contact_id           where x.org_id <> c.org_id),
           (select count(*) from mandates x           join contacts c on c.id = x.owner_contact_id     where x.org_id <> c.org_id),
           (select count(*) from properties x         join contacts c on c.id = x.owner_contact_id     where x.org_id <> c.org_id),
           (select count(*) from properties x         join contacts c on c.id = x.developer_contact_id where x.org_id <> c.org_id),
           (select count(*) from contacts x           join contacts c on c.id = x.merged_into_id       where x.org_id <> c.org_id))
  union all
  -- 0139: and none names a contact that does not exist (0125 / 0129's reason:
  -- the joins above cannot see a dangling id a replica-mode restore loaded).
  select 'INTEGRITY: no lead, deal, offer, share link, requirement, mandate, listing or merge pointer names a contact that does not exist (0139)', '0',
         (select count(*)::text from (
             select 1 from leads x where x.contact_id is not null and not exists (select 1 from contacts c where c.id = x.contact_id)
           union all
             select 1 from deals x
              where (x.buyer_contact_id is not null and not exists (select 1 from contacts c where c.id = x.buyer_contact_id))
                 or (x.seller_contact_id is not null and not exists (select 1 from contacts c where c.id = x.seller_contact_id))
           union all
             select 1 from offers x where x.contact_id is not null and not exists (select 1 from contacts c where c.id = x.contact_id)
           union all
             select 1 from share_links x where x.contact_id is not null and not exists (select 1 from contacts c where c.id = x.contact_id)
           union all
             select 1 from buyer_requirements x where not exists (select 1 from contacts c where c.id = x.contact_id)
           union all
             select 1 from mandates x where x.owner_contact_id is not null and not exists (select 1 from contacts c where c.id = x.owner_contact_id)
           union all
             select 1 from properties x
              where (x.owner_contact_id is not null and not exists (select 1 from contacts c where c.id = x.owner_contact_id))
                 or (x.developer_contact_id is not null and not exists (select 1 from contacts c where c.id = x.developer_contact_id))
           union all
             select 1 from contacts x where x.merged_into_id is not null and not exists (select 1 from contacts c where c.id = x.merged_into_id)) d)
  union all
  -- 0139: and the schema itself — a restore that brought back a single-column
  -- key onto contacts reads above 0 here even while the data is clean.
  select 'SECURITY: every foreign key onto contacts is bound to the contact''s organisation (0139)', '0',
         (select count(*)::text from pg_constraint
           where contype = 'f' and confrelid = 'public.contacts'::regclass and array_length(conkey, 1) = 1)
  union all
  -- 0141: a price-list version and the bulk reprice it records commit as ONE
  -- transaction (record_price_list_version, SECURITY INVOKER): the container
  -- and its units locked FOR NO KEY UPDATE (units in id order), the UPDATE's
  -- row count checked, the per-unit trail counted, and the per-unit line left
  -- to trg_price_history. Read as code — block and line comments stripped. A
  -- restore that brought back a body without them reads false.
  select 'INTEGRITY: a price-list version and the reprice it records commit together, one per-unit line each (0141)', 'true',
         coalesce((select not p.prosecdef
                          and c.code ~ 'p\.kind in \(''project'', ''phase''\)\s+for no key update;'
                          and c.code ~ 'order by u\.id\s+for no key update;'
                          and c.code ~ 'get diagnostics v_rows = row_count;\s+if v_rows <> v_changed then'
                          and c.code ~ 'e\.event_type = ''price_changed''\s+and e\.occurred_at = now\(\)'
                          and c.code !~* 'insert\s+into\s+(public\.)?events[^;]*price_changed'
                     from pg_proc p
                     cross join lateral (select regexp_replace(regexp_replace(p.prosrc, '/\*.*?\*/', '', 'g'), '--[^\n]*', '', 'g') as code) c
                    where p.oid = to_regprocedure('public.record_price_list_version(uuid, uuid, text, text, numeric, text, jsonb)')), false)::text
  union all
  -- 0141: and one version answers one submission — a retry is answered, not
  -- applied twice, only while the operation id is unique per organisation
  select 'INTEGRITY: a price-list operation id is unique per organisation (0141)', 'true',
         coalesce((select i.indisunique and i.indisvalid
                          and pg_get_indexdef(i.indexrelid) ~ '\(org_id, operation_id\)$'
                     from pg_index i
                    where i.indexrelid = to_regclass('public.price_lists_org_operation_key')), false)::text
  union all
  -- Every slip row must still have BOTH its files. Catches a DB-only restore (§1.2),
  -- where the row survives and asserts a signature whose bytes no longer exist.
  -- signature_path / pdf_path equal storage.objects.name exactly (no bucket prefix).
  --
  -- ⚠️ THESE THREE CHECK METADATA, NOT BYTES — AND THAT IS A KNOWN FALSE PASS.
  -- Proven in the 2026-08-05 drill: `data.sql` restores `storage.objects` ROWS,
  -- so on a restore where no file was ever copied all three still report
  -- "0 missing" while every byte is absent. They catch a DB-only restore that
  -- also skipped storage.objects; they do NOT catch one that restored the
  -- metadata and not the files, which is the likelier accident.
  --
  -- SQL cannot see bucket contents, so this cannot be fixed here. The
  -- byte-level proof is `node scripts/backup/restore-storage.mjs`, which
  -- re-downloads every object and compares SHA-256, plus BACKUP_RESTORE §4
  -- step 7 (download a report through the app and hash it against the
  -- pdf_sha256 in its generation event). Result of both: §4c. Treat a green
  -- result below as "the rows agree with each other", never as "the evidence
  -- survived".
  select 'METADATA ONLY (see note): viewing_slip signature rows', '0 missing',
         (select count(*)::text || ' missing' from viewing_slips vs
          where not exists (select 1 from storage.objects o
                            where o.bucket_id = 'signatures' and o.name = vs.signature_path))
  union all
  select 'METADATA ONLY (see note): viewing_slip PDF rows', '0 missing',
         (select count(*)::text || ' missing' from viewing_slips vs
          where vs.pdf_path is not null
            and not exists (select 1 from storage.objects o
                            where o.bucket_id = 'signatures' and o.name = vs.pdf_path))
  union all
  -- Evidence report PDFs live in `documents` under <org>/reports/evidence-*.
  -- Their bytes are what a commission claim is checked against.
  select 'METADATA ONLY (see note): evidence report rows', '0 missing',
         (select count(*)::text || ' missing' from documents d
          where d.storage_path like '%/reports/evidence-%'
            and not exists (select 1 from storage.objects o
                            where o.bucket_id = 'documents' and o.name = d.storage_path))
)

select kind, check_name, expected, actual, (expected = actual) as pass
from (
  -- a mismatch here may just mean the baseline snapshot is out of date
  select 'row count'::text as kind, check_name, expected::text, actual::text from counts
  -- these hold for ANY correct restore; a failure here is real
  union all select 'invariant', check_name, expected, actual from grant_checks
  union all select 'invariant', check_name, expected, actual from grant_unpinned
  union all select 'invariant', check_name, expected, actual from misc
) all_checks
-- failures first, and within them invariants before baseline counts
order by pass, kind, check_name;
