-- verify-restore.sql — post-restore verification pack
-- See docs/BACKUP_RESTORE.md §4 step 5 and §5.
--
-- Run against the RESTORED project. Every row must read pass = true.
-- Read-only: it asserts, it never writes.
--
-- REGENERATED 2026-08-30 (audit REL-04). The previous pack had drifted ~25
-- migrations behind the schema: it checked 3 of 8 cron jobs, pinned a
-- 13-function grants table frozen before 0024, and its table list predated
-- share links, reservations, buyer requirements and the chain checkpoint —
-- so a restore could verify GREEN while missing five cron jobs and while
-- anon held default-ACL EXECUTE on every function added since (the hosted
-- false-pass mechanism proven in §6b). The grants table below was NOT typed
-- from memory: it was generated by querying a migration-built local database
-- (all 73 migrations applied), which is the same construction CI proves on
-- every push. When migrations change grants, REGENERATE rather than editing
-- by hand — the query is in the comment above the table.
--
-- The output has THREE kinds of check, and the difference matters when you
-- are reading it under pressure:
--
--   invariant  — true of a correct restore regardless of how much data exists:
--                the event chain, the function grants (the TEST-2 surface),
--                cron, bucket visibility, migration history, session timezone.
--                A failure here is REAL.
--   metadata   — rows agreeing with rows. Cannot see bucket contents, so it
--                CANNOT prove a file survived. Green here is not evidence.
--   row count  — compared against the `expected` block below, which is a
--                SNAPSHOT. If production moved on since it was captured, these
--                fail while the restore is perfectly fine.
--
-- So: **re-capture the baseline immediately before a drill** by running
-- scripts/backup/capture-baseline.sql against the SOURCE and pasting its single
-- output row over the `expected` block. Hardcoded counts previously went stale
-- and reported false failures, which is the worst possible signal mid-recovery.
--
-- (`check` is a reserved word in Postgres, hence `check_name`.)

with expected as (
  -- BASELINE — replace via scripts/backup/capture-baseline.sql before a drill.
  select
    1::bigint as orgs,      2::bigint as profiles,   130::bigint as events,
    2::bigint as contacts,  1::bigint as properties, 1::bigint as deals,
    3::bigint as leads,     0::bigint as viewings,   0::bigint as slips,
    0::bigint as documents, 1::bigint as keys,       1::bigint as mandates,
    0::bigint as tasks,     8::bigint as cyprus_config,
    26::bigint as deal_stages, 5::bigint as districts,
    2::bigint as auth_users, 80::bigint as migrations,
    1::bigint as obj_documents, 0::bigint as obj_signatures, 0::bigint as obj_media,
    2::bigint as share_links, 2::bigint as share_link_properties,
    0::bigint as unit_types, 0::bigint as buyer_requirements,
    0::bigint as reservations, 0::bigint as reservation_installments,
    12::bigint as task_kinds, 1::bigint as chain_checkpoints
    -- captured 2026-08-30 from hosted (yjgirvzgoiywdojnpkpd) via
    -- capture-baseline.sql, after the 08-29/30 audit-fix run (0070–0073,
    -- PAF0001 content fixes, test-photo deletion — which is why media
    -- objects read 0). migrations and task_kinds bumped 2026-08-31 for
    -- 0074–0078 — caught by the cloud drill, §4e — and were STALE AGAIN
    -- within hours when 0079 merged (bumped to 79 on 2026-09-01). The pin
    -- is now locked to the migration files by verify-restore.test.ts, so
    -- a migration can no longer land without this line moving (80 as of
    -- 0080, 2026-09-01).
    --
    -- KNOWN CLOUD DELTA (verified 2026-08-31, §4e): on ANY cloud project
    -- — live production included — exactly NINE grants rows fail with
    -- service_role EXECUTE = true where this table (built from a local,
    -- migration-built database) says false: mfa_satisfied, org_mfa_status,
    -- protect_document_columns, protect_profile_columns,
    -- rls_bare_auth_calls, trg_events_hash, trg_price_history,
    -- trg_supersede_deal_nudges, trg_supersede_viewing_nudges — plus, since
    -- 0080 pinned them at service=false (2026-09-01, not yet drill-verified
    -- on cloud): set_updated_at and protect_property_reference, same
    -- mechanism, so ELEVEN rows on a cloud target. That is the
    -- platform's default privileges granting service_role EXECUTE on every
    -- function (HANDOFF's mfa_satisfied note, generalized). service_role
    -- bypasses RLS anyway — the delta is harmless. A cloud run of this
    -- pack that fails ONLY those rows has CONVERGED to production's
    -- own posture: the 2026-08-31 drill proved live production fails the
    -- identical set.
    --
    -- `events` IS THE ONE THAT GOES STALE. It is append-only, so it drifts
    -- upward on every single use of the app and never returns. Check `events`
    -- first when this block looks wrong, and re-capture rather than assuming
    -- a bad restore.
    --
    -- The two rate-limit counter tables (share_link_attempts,
    -- public_listing_attempts) are DELIBERATELY absent: they self-prune on a
    -- rolling window, so any snapshot of them is stale by design and would
    -- manufacture false failures. They still travel in export.mjs.
),

-- ---------- row counts ----------
counts as (
  select 'rows: organizations' as check_name, e.orgs as expected, (select count(*) from organizations) as actual from expected e
  union all select 'rows: profiles',      e.profiles,      (select count(*) from profiles) from expected e
  union all select 'rows: events',        e.events,        (select count(*) from events) from expected e
  union all select 'rows: contacts',      e.contacts,      (select count(*) from contacts) from expected e
  union all select 'rows: properties',    e.properties,    (select count(*) from properties) from expected e
  union all select 'rows: deals',         e.deals,         (select count(*) from deals) from expected e
  union all select 'rows: leads',         e.leads,         (select count(*) from leads) from expected e
  union all select 'rows: viewings',      e.viewings,      (select count(*) from viewings) from expected e
  union all select 'rows: viewing_slips', e.slips,         (select count(*) from viewing_slips) from expected e
  union all select 'rows: documents',     e.documents,     (select count(*) from documents) from expected e
  union all select 'rows: property_keys', e.keys,          (select count(*) from property_keys) from expected e
  union all select 'rows: mandates',      e.mandates,      (select count(*) from mandates) from expected e
  union all select 'rows: tasks',         e.tasks,         (select count(*) from tasks) from expected e
  union all select 'rows: share_links',   e.share_links,   (select count(*) from share_links) from expected e
  union all select 'rows: share_link_properties', e.share_link_properties, (select count(*) from share_link_properties) from expected e
  union all select 'rows: unit_types',    e.unit_types,    (select count(*) from unit_types) from expected e
  union all select 'rows: buyer_requirements', e.buyer_requirements, (select count(*) from buyer_requirements) from expected e
  union all select 'rows: reservations',  e.reservations,  (select count(*) from reservations) from expected e
  union all select 'rows: reservation_installments', e.reservation_installments, (select count(*) from reservation_installments) from expected e
  union all select 'seed: task_kinds',    e.task_kinds,    (select count(*) from task_kinds) from expected e
  union all select 'rows: events_chain_checkpoint', e.chain_checkpoints, (select count(*) from events_chain_checkpoint) from expected e
  union all select 'seed: cyprus_config', e.cyprus_config, (select count(*) from cyprus_config) from expected e
  union all select 'seed: deal_stages',   e.deal_stages,   (select count(*) from deal_stages) from expected e
  union all select 'seed: districts',     e.districts,     (select count(*) from districts) from expected e
  union all select 'auth: users',         e.auth_users,    (select count(*) from auth.users) from expected e
  union all select 'migrations: rows',    e.migrations,    (select count(*) from supabase_migrations.schema_migrations) from expected e
  union all select 'storage: documents objects',  e.obj_documents,  (select count(*) from storage.objects where bucket_id = 'documents') from expected e
  union all select 'storage: signatures objects', e.obj_signatures, (select count(*) from storage.objects where bucket_id = 'signatures') from expected e
  union all select 'storage: media objects',      e.obj_media,      (select count(*) from storage.objects where bucket_id = 'media') from expected e
),

-- ---------- function grants: the TEST-2 surface ----------
-- A restore that silently drops OR GAINS one of these looks perfectly healthy
-- on screen. GAINS are the likelier accident on hosted: default privileges
-- hand anon EXECUTE on every newly created function (§6b grant probe), so a
-- restore that replays migrations through a path that misses a revoke leaves
-- a sweep or reporting function anon-callable.
--
-- GENERATED 2026-08-30 from a migration-built local DB at 0073 — regenerate,
-- do not hand-edit:
--   select distinct p.proname, p.prosecdef,
--          has_function_privilege('anon', p.oid, 'EXECUTE'),
--          has_function_privilege('authenticated', p.oid, 'EXECUTE'),
--          has_function_privilege('service_role', p.oid, 'EXECUTE')
--     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--    where n.nspname = 'public' and (p.prosecdef or <project fn list>);
grants_expected(fn, secdef, anon, auth, service) as (values
  -- chain of custody
  ('verify_events_chain',      true,  false, false, true),
  ('run_chain_checks',         true,  false, false, true),
  ('run_chain_checks_full',    true,  false, false, true),
  ('advance_chain_checkpoint', true,  false, false, true),
  ('ensure_events_partitions', true,  false, false, true),
  ('events_partition_health',  true,  false, false, true),
  -- sweeps: cron runs them as postgres; nothing else may call them.
  -- expire_mandates: service_role = false since 0022 (undocumented hosted
  -- grants encoded drift; pg_cron needs no grant).
  ('expire_mandates',            true, false, false, false),
  ('create_followup_nudges',     true, false, false, true),
  ('expire_reservations',        true, false, false, true),
  ('warn_expiring_reservations', true, false, false, true),
  ('remind_due_installments',    true, false, false, true),
  ('raise_key_recall_tasks',     true, false, false, true),
  ('nudge_threshold',            true, false, false, true),
  -- RLS helpers and the 2FA gate. mfa_satisfied is pinned to the
  -- MIGRATION-BUILT value; hosted historically carries an extra service_role
  -- EXECUTE (pre-existing, noted at 0059) — if this row ALONE fails against a
  -- hosted-derived target, compare against that note before treating it as a
  -- bad restore.
  ('current_org_id',   true, false, true, false),
  ('current_role_gnk', true, false, true, false),
  ('mfa_satisfied',    true, false, true, false),
  ('org_mfa_status',   true, false, true, false),
  ('rls_aal2_coverage',        true, false, false, true),
  ('rls_bare_auth_calls',      true, false, true,  false),
  ('rls_bare_helper_calls',    true, false, false, true),
  ('rls_hoisted_policy_count', true, false, false, true),
  -- cron visibility (0074): the admin-dashboard health read, service only
  ('cron_health',          true,  false, false, true),
  -- app RPCs
  ('next_reference',       true,  false, true, true),
  ('record_key_movement',  true,  false, true, true),
  ('move_deal_to_stage',   false, false, true, true),
  ('add_deal_stage',       false, false, true, true),
  ('reorder_stage',        false, false, true, true),
  ('admin_dashboard_stats',false, false, true, true),
  -- reporting engine (0065) — SECURITY INVOKER by design (the MV lesson)
  ('report_agent_performance', false, false, true, true),
  ('report_source_roi',        false, false, true, true),
  ('report_time_to_close',     false, false, true, true),
  ('report_stage_conversion',  false, false, true, true),
  ('report_price_reductions',  false, false, true, true),
  ('report_citation',          false, false, true, true),
  ('published_below_threshold',false, false, true, true),
  -- the deliberate anon surface: share links (0023/0041) and the public
  -- listing feed (0066/0073). anon = TRUE is unique to these five and is the
  -- point — a restore that DROPS these grants kills every live proposal link
  -- and the marketing feed silently, which is why they are pinned.
  ('resolve_share_link',      true, true, true, true),
  ('note_share_link_miss',    true, true, true, true),
  ('public_listings',         true, true, true, true),
  ('public_listings_etag',    true, true, true, true),
  ('note_public_listing_hit', true, true, true, true),
  -- trigger bodies: callable by nobody over PostgREST (0007/0021)
  ('trg_events_hash',              true, false, false, false),
  -- + the two invoker trigger bodies 0080 brought into the same posture,
  -- pinned to the MIGRATION-BUILT value (on cloud these two join the nine
  -- service_role default-ACL deltas in the KNOWN CLOUD DELTA note above)
  ('set_updated_at',               false, false, false, false),
  ('protect_property_reference',   false, false, false, false),
  ('trg_price_history',            true, false, false, false),
  ('trg_supersede_deal_nudges',    true, false, false, false),
  ('trg_supersede_viewing_nudges', true, false, false, false),
  ('protect_document_columns',     true, false, false, false),
  ('protect_profile_columns',      true, false, false, false)
),
grants_actual as (
  select distinct p.proname::text as fn, p.prosecdef as secdef,
         has_function_privilege('anon', p.oid, 'EXECUTE') as anon,
         has_function_privilege('authenticated', p.oid, 'EXECUTE') as auth,
         has_function_privilege('service_role', p.oid, 'EXECUTE') as service
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
),
grant_checks as (
  select 'grants: ' || ge.fn as check_name,
         ge.secdef::text || '/' || ge.anon::text || '/' || ge.auth::text || '/' || ge.service::text as expected,
         coalesce(ga.secdef::text || '/' || ga.anon::text || '/' || ga.auth::text || '/' || ga.service::text, 'FUNCTION MISSING') as actual
  from grants_expected ge left join grants_actual ga on ga.fn = ge.fn
),
-- ---------- the reverse direction: FAIL CLOSED on the unpinned ----------
-- The join above only examines functions somebody remembered to pin — the
-- 2026-09-01 review caught it blind to 0074's cron_health() eleven minutes
-- after the list was generated. Any public SECURITY DEFINER function, or any
-- function anon can execute, that is NOT in grants_expected fails here: the
-- two classes where a silently-unchecked function is a hole, not a nit.
-- (authenticated-EXECUTE invoker functions are deliberately out of scope —
-- that is the default posture for app RPCs and would drown the signal.)
grant_unpinned as (
  select distinct 'grants: UNPINNED ' || p.proname as check_name,
         'pinned in grants_expected' as expected,
         'secdef=' || p.prosecdef::text
           || ' anon=' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
           || ' — add the row (regenerate the list) before trusting this pack' as actual
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and (p.prosecdef or has_function_privilege('anon', p.oid, 'EXECUTE'))
    and not exists (select 1 from grants_expected ge where ge.fn = p.proname)
    -- extension-owned functions (PostGIS ships hundreds, anon-executable by
    -- design) are the platform's surface, not this schema's — out of scope
    and not exists (select 1 from pg_depend d
                    where d.classid = 'pg_proc'::regclass and d.objid = p.oid
                      and d.refclassid = 'pg_extension'::regclass and d.deptype = 'e')
),

-- ---------- everything else ----------
misc as (
  select 'timezone is UTC (see BACKUP_RESTORE 1.3)' as check_name,
         'UTC' as expected, current_setting('TimeZone') as actual
  union all
  select 'migrations: non_filename_versions', '0',
         (select count(*)::text from supabase_migrations.schema_migrations where version !~ '^[0-9]{4}$')
  union all
  -- ALL EIGHT cron jobs (the previous pack checked three, so a restore that
  -- lost the other five verified green — audit REL-04). pg_cron jobs are in
  -- NO dump; after a restore every one must be recreated from the migrations
  -- (§4b.4), and this is the list that proves it happened.
  select 'cron: ' || j.jobname || ' active', 'true',
         coalesce((select active::text from cron.job where jobname = j.jobname), 'JOB MISSING')
  from (values ('expire-mandates'), ('followup-nudges'), ('verify-events-chain'),
               ('verify-events-chain-full'), ('expire-reservations'),
               ('warn-expiring-reservations'), ('remind-due-installments'),
               ('ensure-events-partitions')) as j(jobname)
  union all
  select 'cron: exactly 8 jobs, none extra', '8',
         (select count(*)::text from cron.job)
  union all
  select 'storage: media bucket is public (migration 0008)', 'true',
         coalesce((select public::text from storage.buckets where id = 'media'), 'BUCKET MISSING')
  union all
  select 'storage: documents bucket is private', 'false',
         coalesce((select public::text from storage.buckets where id = 'documents'), 'BUCKET MISSING')
  union all
  select 'storage: signatures bucket is private', 'false',
         coalesce((select public::text from storage.buckets where id = 'signatures'), 'BUCKET MISSING')
  union all
  -- events partitions must live OUTSIDE public (0063): pg_default_acl grants
  -- anon TRUNCATE-bearing rights on anything created in public, and RLS does
  -- not gate TRUNCATE. A restore that recreated them in public is exposed.
  select 'partitions: all events partitions in events_parts schema', '0',
         (select count(*)::text
            from pg_inherits i
            join pg_class c on c.oid = i.inhrelid
            join pg_namespace n on n.oid = c.relnamespace
           where i.inhparent = 'public.events'::regclass
             and n.nspname <> 'events_parts')
  union all
  select 'partitions: events_partition_health() is empty', '0',
         (select count(*)::text from events_partition_health())
  union all
  -- The one that matters most. False here means re-read §1.3 BEFORE assuming corruption:
  -- a non-UTC session TimeZone breaks verification on perfectly intact data.
  select 'INTEGRITY: event chain verifies for every org', 'true',
         (select coalesce(bool_and(verify_events_chain(id)), true)::text from organizations)
  union all
  -- Every slip row must still have BOTH its files. Catches a DB-only restore (§1.2),
  -- where the row survives and asserts a signature whose bytes no longer exist.
  -- signature_path / pdf_path equal storage.objects.name exactly (no bucket prefix).
  --
  -- ⚠️ THESE THREE CHECK METADATA, NOT BYTES — AND THAT IS A KNOWN FALSE PASS.
  -- Proven in the 2026-08-05 drill: `data.sql` restores `storage.objects` ROWS,
  -- so on a restore where no file was ever copied all three still report
  -- "0 missing" while every byte is absent. They catch a DB-only restore that
  -- also skipped storage.objects; they do NOT catch one that restored the
  -- metadata and not the files, which is the likelier accident.
  --
  -- SQL cannot see bucket contents, so this cannot be fixed here. The
  -- byte-level proof is `node scripts/backup/restore-storage.mjs`, which
  -- re-downloads every object and compares SHA-256, plus BACKUP_RESTORE §4
  -- step 7 (download a report through the app and hash it against the
  -- pdf_sha256 in its generation event). Result of both: §4c. Treat a green
  -- result below as "the rows agree with each other", never as "the evidence
  -- survived".
  select 'METADATA ONLY (see note): viewing_slip signature rows', '0 missing',
         (select count(*)::text || ' missing' from viewing_slips vs
          where not exists (select 1 from storage.objects o
                            where o.bucket_id = 'signatures' and o.name = vs.signature_path))
  union all
  select 'METADATA ONLY (see note): viewing_slip PDF rows', '0 missing',
         (select count(*)::text || ' missing' from viewing_slips vs
          where vs.pdf_path is not null
            and not exists (select 1 from storage.objects o
                            where o.bucket_id = 'signatures' and o.name = vs.pdf_path))
  union all
  -- Evidence report PDFs live in `documents` under <org>/reports/evidence-*.
  -- Their bytes are what a commission claim is checked against.
  select 'METADATA ONLY (see note): evidence report rows', '0 missing',
         (select count(*)::text || ' missing' from documents d
          where d.storage_path like '%/reports/evidence-%'
            and not exists (select 1 from storage.objects o
                            where o.bucket_id = 'documents' and o.name = d.storage_path))
)

select kind, check_name, expected, actual, (expected = actual) as pass
from (
  -- a mismatch here may just mean the baseline snapshot is out of date
  select 'row count'::text as kind, check_name, expected::text, actual::text from counts
  -- these hold for ANY correct restore; a failure here is real
  union all select 'invariant', check_name, expected, actual from grant_checks
  union all select 'invariant', check_name, expected, actual from grant_unpinned
  union all select 'invariant', check_name, expected, actual from misc
) all_checks
-- failures first, and within them invariants before baseline counts
order by pass, kind, check_name;
